### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/server-tools#1008]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Repository split
As talked in [this mailing list thread](https://odoo-community.org/groups/tools-22/tools-44031?mode=thread) this repository is very crowded, so for 11.0, an split has been done across several repositories. Please check current spreadsheet for the initial distribution plan. If there's a module not included here or that you have doubts, please ask in this issue:

https://docs.google.com/spreadsheets/d/1Xg95cW4TFMf_Lo5i_CZC_qOOfN8RgxPRc0LJTLTkdUI/edit?usp=sharing

# Modules to migrate

- [ ] admin_technical_features
- [ ] attachment_base_synchronize
- [x] auditlog - By @etobella - #1040 
- [ ] auth_admin_passkey
- [x] auth_brute_force - By @Yajo - https://github.com/OCA/server-auth/pull/19
- [x] auth_dynamic_groups - Moved to OCA/server-auth - By @NL66278 - OCA/server-auth#98
- [ ] auth_from_http_basic
- [ ] auth_from_http_basic_logout
- [x] auth_from_http_remote_user - By @TDu - OCA/server-auth#7
- [x] auth_session_timeout - By @zaoral - OCA/server-auth#32
- [x] auth_signup_verify_email - @simahawk OCA/server-auth#8
- [ ] auth_supplier
- [x] auth_totp - By @mreficent - OCA/server-auth#17
- [x] auth_totp_password_security - By @mreficent - OCA/server-auth#18
- [x] auth_user_case_insensitive - By @mgosai - OCA/server-auth#35
- [x] auto_backup - By @astirpe - #1158 
- [x] base_cron_exclusion - By @bodedra - in #1156 
- [ ] base_custom_info - Improve usability with polymorphic widget?
- [x] base_exception - By @mourad-ehm - #1025 
- [x] base_export_manager - By @Yajo - https://github.com/OCA/server-ux/pull/22
- [x] base_external_dbsource - By @sergio-teruel - OCA/server-backend#9
- [ ] base_external_dbsource_firebird
- [x] base_external_dbsource_mssql - By @sergio-teruel - OCA/server-backend#6
- [x] base_external_dbsource_mysql - By @sergio-teruel - OCA/server-backend#7
- [ ] base_external_dbsource_odbc
- [ ] base_external_dbsource_oracle
- [x] base_external_dbsource_sqlite - By @sergio-teruel - OCA/server-backend#8
- [x] base_fontawesome - By @etobella - #1361
- [ ] base_import_default_enable_tracking - By @dsolanki-initos - #1955
- [ ] base_import_match - By @misern2 - OCA/server-backend#17
- [x] base_import_security_group - By @i-vyshnevska - OCA/server-ux#58 
- [ ] base_kanban_stage - By @fshah-initos - #1958
- [ ] base_kanban_stage_state
- [ ] base_locale_uom_default - By @dsolanki-initos - #1956 
- [ ] base_manifest_extension
- [ ] base_multi_image
- [x] base_name_search_improved - By @zaoral - #1325
- [x] base_optional_quick_create - By @fmdl - OCA/server-ux#14
- [ ] base_report_auto_create_qweb
- [x] base_search_fuzzy - By @cubells - #1284 
- [x] base_suspend_security - By @BT-fgarbely - OCA/server-backend#5
- [x] base_technical_features - By @stefanrijnhart - OCA/server-ux#2
- [x] base_technical_user - By @hugosantosred - #1147 
- [x] ~~base_user_gravatar~~ Included in core
- [x] base_user_role - By @novawish - OCA/server-backend#1
- [x] base_view_inheritance_extension - By @sergio-teruel - #1407 
- [x] configuration_helper - By @grindtildeath - #1261 
- [x] database_cleanup by @hbrunn #1009 
- [x] date_range - By @etobella / @lmignon - OCA/server-ux#3
- [x] datetime_formatter - By @oleksandrpaziuk - #1133 
- [x] dbfilter_from_header - By @yelizariev - #1182 
- [x] dead_mans_switch_client - By @aisopuro - #1277 
- [x] disable_odoo_online - By @hieulucky111 - OCA/server-brand#1
- [ ] email_template_template
- [ ] fetchmail_attach_from_folder
- [x] fetchmail_notify_error_to_sender - ~~By @haidd - #1238~~ - By @nedaszilinskas - #1306 
- [x] html_image_url_extractor - By @tarteo - #1155 
- [x] html_text - By @tarteo - #1154 
- [ ] import_odbc
- [ ] ir_config_parameter_viewer
- [x] keychain - By @mart-e - OCA/server-auth#5
- [ ] kpi
- [ ] language_path_mixin
- [x] letsencrypt - By @acysos - #1244 
- [ ] mail_environment
- [x] mail_log_message_to_process > fetchmail_incoming_log - By @hveficent - #1402
- [x] mass_editing - By @jnegrete - OCA/server-ux#5
- [ ] mass_sorting
- [ ] menu_technical_info
- [x] module_auto_update - By @Yajo -  #1118
- [ ] module_prototyper
- [x] onchange_helper - By @astirpe - #1128 
- [x] password_security - By @smurf-U - OCA/server-auth#3
- [x] record_archiver - By @arkostyuk  - OCA/server-tools#1381
- [x] res_config_settings_enterprise_remove - By @astirpe - OCA/server-brand#2
- [x] scheduler_error_mailer - By @AMhadhbi - #1297 
- [ ] security_protector
- [x] sentry - By @njeudy - #1082
- [x] sequence_check_digit - By @etobella - OCA/server-ux#1
- [ ] server_env_base_external_referentials
- [x] server_environment - ~~By @TDu - #1051~~ - By @simahawk - OCA/server-env#4
- [ ] server_environment_files_sample
- [x] server_environment_ir_config_parameter - ~~By @TDu - #1058~~ - By @simahawk - OCA/server-env#8
- [x] sql_request_abstract - By @hveficent - #1323
- [ ] super_calendar - ~~By @ddufresne - #1173~~
- [x] test_configuration_helper - By @grindtildeath - #1261
- [ ] user_immutable
- [ ] user_threshold - By @dsolanki-initos - #1954 
- [ ] users_ldap_groups
- [ ] users_ldap_mail
- [ ] users_ldap_populate
- [ ] webhook  - By @dsolanki-initos - #1961

**Comment by smurf-U** [comment]
[MIG]11.0 password security #1022

**Comment by smurf-U** [comment]
[MIG]11.0 password security #1022

**Comment by novawish** [comment]
Hello @pedrobaeza,
I did not see (in [here](https://docs.google.com/spreadsheets/d/1Xg95cW4TFMf_Lo5i_CZC_qOOfN8RgxPRc0LJTLTkdUI/edit?usp=sharing)) which repository that module `base_user_role` should belonged to.

Should I create a new PR to `server-backend` as you mentioned in https://github.com/OCA/server-tools/pull/1036 or I just keep the PR like that?

**Comment by pedrobaeza** [comment]
That's because that module doesn't exist when the list was created. My opinion is that it should go to server-ux

**Comment by simahawk** [comment]
mail_environment @simahawk https://github.com/OCA/server-tools/pull/1074

**Comment by zamberjo** [comment]
@pedrobaeza **auth_brute_force** is not included

**Comment by pedrobaeza** [comment]
@simahawk please don't include `- [ ]` in your comment, as it adds another task to do in the issue summary link, which is not correct, as there's already a bullet in the main comment.

@zamberjo it was in the list... I have included a link to your PR there.

**Comment by pedrobaeza** [comment]
@zamberjo or are you talking about the split list? I'm thinking that the module should go to server-auth.

**Comment by njeudy** [comment]
sentry @njeudy #1082

**Comment by nadiaafa** [comment]
@pedrobaeza i will work on auth_session_timeout

**Comment by pedrobaeza** [comment]
@nadiaafa that module should go to server-auth

**Comment by jlzhou** [comment]
base_external_dbsource
 base_external_dbsource_mssql
 base_external_dbsource_mysql
 base_external_dbsource_odbc
 base_external_dbsource_oracle
 base_external_dbsource_sqlite

#1107

**Comment by pedrobaeza** [comment]
@jlzhou maybe this should be to OCA/server-backend?

**Comment by jlzhou** [comment]
@pedrobaeza Not sure, you are the boss. :)

**Comment by pedrobaeza** [comment]
hehe, well, I have the same vote as any contributor. Looking at the split spreadsheet: https://docs.google.com/spreadsheets/d/1Xg95cW4TFMf_Lo5i_CZC_qOOfN8RgxPRc0LJTLTkdUI/edit#gid=0, people had the same doubts about this. Let's see if someone more have a special opinion about this. @lasley @dreispt ? If not, as you are the one making the PR, you can decide by yourself.

**Comment by elicoidal** [comment]
> maybe this should be to OCA/server-backend?

I like server-backend but not a big deal as this is just at the limit

**Comment by lasley** [comment]
I agree with `server-backend`

**Comment by astirpe** [comment]
onchange_helper https://github.com/OCA/server-tools/pull/1128

**Comment by simahawk** [comment]
auth_signup_verify_email https://github.com/OCA/server-auth/pull/8

**Comment by astirpe** [comment]
res_config_settings_enterprise_remove: https://github.com/OCA/server-brand/pull/2

**Comment by max3903** [comment]
Any issue if base_cron_exclusion stays in server-tools? Or do you have a better candidate?

**Comment by astirpe** [comment]
auto_backup #1158

**Comment by bodedra** [comment]
base_cron_exclusion #1156

**Comment by ddufresne** [comment]
I will work on super_calendar

**Comment by ddufresne** [comment]
super_calendar https://github.com/OCA/server-tools/pull/1173

**Comment by JonCup** [comment]
I didn't see anything in the spreadsheet about Webhook, did that move, is there an anyone planing on working on that? it sounds very useful for a number of things.

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/webhook

**Comment by JonCup** [comment]
@pedrobaeza it does not appear to have ever had any code in there.

**Comment by pedrobaeza** [comment]
See the PRs

**Comment by youring** [comment]
base_name_search_improved seems unlisted since v10, and some other very useful module like base_import_odoo, field_char_transformed, qweb_usertime...born for v8, although created after this list, IMHO, should be taken care here or add a note for obsoletion. @pedrobaeza @dreispt @hbrunn Thanks for your contrib and killer-grade tools.

**Comment by pedrobaeza** [comment]
The list is copied from v10. If they aren't in that branch when the new branch is created, then they won't be in the list. If you want to migrate one of them directly from v8 to v11, no problem in adding them. For now, we are not going to add them if there are no intentions of migrating them.

**Comment by haidd** [comment]
fetchmail_notify_error_to_sender [#1238](https://github.com/OCA/server-tools/pull/1238)

**Comment by MiquelRForgeFlow** [comment]
auth_totp_password_security https://github.com/OCA/server-auth/pull/18

**Comment by aisopuro** [comment]
`dead_mans_switch_client` #1277

**Comment by BT-fgarbely** [comment]
Hello @pedrobaeza
I want to migrate base_suspend_security to v11.0.
I think I have to create the PR in OCA/server-backend

**Comment by pedrobaeza** [comment]
@BT-fgarbely yeah, that's the proposed target repository. Go ahead and good luck!

**Comment by AMhadhbi** [comment]
I will work on scheduler_error_mailer

**Comment by pedrobaeza** [comment]
Great, noted

**Comment by zaoral** [comment]
I will work on base_name_search_improved

**Comment by zaoral** [comment]
i will work on auth_session_timeout (in to server-auth)

**Comment by jlzhou** [comment]
I am working on menu_technical_info, I think it should be in server-ux repo, but I don't know how to move the module code properly with history, pls advise, thanks.

**Comment by gurneyalex** [comment]
@pedrobaeza is it ok for me to add this module https://github.com/OCA/server-tools/tree/10.0/sql_export to the migration list? Sounds a good candidate for staying in server-tools.

**Comment by pedrobaeza** [comment]
Yeah, it's similar to other options:

* On https://github.com/OCA/server-backend we have several modules for importing from other DBs. Is the same export than import?

* On OCA/server-ux, there are things that change the interface or add options to the interface (look `mass_editing`)

so if you decide to continue here, it's OK.

**Comment by alexey-pelykh** [comment]
@pedrobaeza what to do if module is in 10.0 and it's needed in 12.0 - port only to 12.0?

**Comment by pedrobaeza** [comment]
@alexey-pelykh yes, you don't need to migrate to all intermediate versions (unless you want). On the migration steps, you have to change the source branch from 11.0 to 10.0 for pointing to where the module is migrated.

**Comment by misern2** [comment]
Hi @pedrobaeza .

I want to migrate the base_import_search module to V11 and I don't find it in the google doc.
Which is the best place, server-backend repo ?

**Comment by pedrobaeza** [comment]
@misern2 do you mean `base_import_match`?

**Comment by misern2** [comment]
@pedrobaeza yes!. Sorry for the mistake .. base_import_match ....

**Comment by pedrobaeza** [comment]
Yes, OCA/server-backend or this one are good hosters, as can't be easily classified.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, add to the list base_fontawesome - By @etobella - #1361 that is already migrated and merged

Please, add to the list base_name_search_improved - By @zaoral - #1325 that is already migrated and merged

Please, add to the list mail_log_message_to_process that is renamed as -> fetchmail_incoming_log - By @hveficent - #1402 that is already migrated and merged

Please, could you move up key module in the list so that it is sorted correctly in alphabetical order

Please, check onchange_helper - By @astirpe - #1128 because it is already merged

Please, check password_security - By @smurf-U - OCA/server-auth#3

Please, check sentry - By @njeudy - #1082 because it is already merged

Please, add to the list sql_request_abstract - By @hveficent - #1323 that is already migrated and merged

Please, check test_configuration_helper - By @grindtildeath - #1261

**Comment by emagdalenaC2i** [comment]
Please, check auth_from_http_remote_user - By @TDu - OCA/server-auth#7 that is already merged

super_calendar - By @ddufresne - #1173 is closed

**Comment by mvaled** [comment]
@pedrobaeza 

I don't see any PR for `module_prototyper`.  In the [document](https://docs.google.com/spreadsheets/d/1Xg95cW4TFMf_Lo5i_CZC_qOOfN8RgxPRc0LJTLTkdUI/edit#gid=0) is still listed in the repo.

Is someone working on it, or could I open a PR for it.  

Also I don't see even a checkbox for it in #1368.  Was this addon split to somewhere else?

**Comment by pedrobaeza** [comment]
That's because this issue is auto-populated from previous branch content when the new branch is created, and that module wasn't merged when that happens.

**Comment by njeudy** [comment]
@mvaled did you work on module_prototyper migration ? want to start V12 migration :)

**Comment by mvaled** [comment]
@njeudy No, I didn't.  Feel free to start. :+1:

**Comment by hugho-ad** [comment]
Hello

Why base_export_security is not in the list?

**Comment by hugho-ad** [comment]
Also I didn't see it at google doc, Was deprecated?

**Comment by hugho-ad** [comment]
@pedrobaeza do you know what happens with base_export_security? why it's not on the list?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by dsolanki-initos** [comment]
Hello all,
Here is the PR #1951 for the migrated module mass_sorting to v11.

**Comment by fshah-initos** [comment]
Hello all,

I've migrated the module base_custom_info and here is the pull request.
https://github.com/OCA/server-tools/pull/1952

**Comment by fshah-initos** [comment]
Hello all,

I've migrated the module user_immutable and here is the pull request
https://github.com/OCA/server-tools/pull/1953

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated the module user_threshold and here is the PR #1954

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated the module base_import_default_enable_tracking to v11 and here is PR #1955

**Comment by dsolanki-initos** [comment]
Hello, I have migrated the module base_locale_uom_default to v11 and here is the PR  #1956

**Comment by fshah-initos** [comment]
Hello all,
I have migrated the module base_kanban_stage to v11 and here is the PR https://github.com/OCA/server-tools/pull/1958

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated the module webhook to v11 and here is the PR #1961

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated the module users_ldap_groups to v11 and here is the PR #1962

**Comment by antonioburic** [comment]
Hi all,
the module autovacuum_message_attachment has been migrated/backported from version 12, here is the PR: #2148
