### ISSUE TITLE
Migration to version 8

### ISSUE THREAD

**Issue by max3903** [OCA/server-tools#168]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8
# Modules to migrate
- [x] auth_admin_passkey
- [ ] auth_from_http_basic
- [ ] auth_from_http_basic_logout
- [x] base_external_dbsource by @Lauris-v in #41 
- [ ] base_optional_quick_create
- [ ] configuration_helper
- [x] cron_run_manually
- [x] database_cleanup
- [x] dbfilter_from_header
- [ ] defer_parent_store_computation_import
- [x] disable_openerp_online
- [ ] document_export_from_db
- [ ] email_template_dateutil
- [ ] email_template_template
- [x] fetchmail_attach_from_folder
- [x] import_odbc by @Lauris-v in #41
- [x] mail_environment
- [x] mass_editing
- [ ] module_parent_dependencies
- [x] scheduler_error_mailer
- [ ] sentry_logger
- [x] server_environment
- [ ] server_environment_files
- [ ] sql_export #351 
- [x] super_calendar by @alejandrosantana in #139 
- [ ] tree_view_record_id
- [ ] users_ldap_groups
- [x] users_ldap_mail
- [x] users_ldap_populate
- [ ] web_context_tunnel
# Obsolete and deprecated modules

**Comment by pedrobaeza** [comment]
Closing as this is not in use anymore.
