### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/server-tools#271]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] admin_technical_features by @njeudy in #318
- [x] auditlog - ~~By @holdenrehg - #454~~ - By @sebalix - #603 
- [ ] auth_admin_passkey - By @rvalyi - #522
- [x] auth_brute_force - By @Yajo - #1255  
- [ ] auth_dynamic_groups
- [ ] auth_from_http_basic
- [ ] auth_from_http_basic_logout
- [x] auth_from_http_remote_user @lmignon #457
- [ ] auth_saml - #274
- [x] auth_signup_verify_email - by @Yajo #436 
- [x] auth_supplier - By @Yajo - #434 
- [x] auto_backup - by @lasley - #526 
- [X] base_concurrency - #342
- [x] base_custom_info - By @Yajo - #435
- [x] ~~base_debug4all~~ - Not needed anymore (in core) - Removed in #573 
- [x] base_external_dbsource by @naousse in #513 
- [ ] base_field_serialized
- [x] base_import_match - By @cubells - #649
- [ ] base_ir_filters_active
- [x] base_multi_image - Assigned to @atchuthan - #402
- [x] base_name_search_improved - By @nicomacr - #621 
- [x] base_optional_quick_create #387, see also https://github.com/OCA/server-tools/pull/300#issuecomment-159908187
- [ ] base_search_fuzzy - By @darshan-serpent - #675 
- [x] base_suspend_security - #333
- [x] base_report_auto_create_qweb - By @damdam-s - #438
- [x] base_user_gravatar - #338
- [x] base_user_role - By @sebalix - #641 
- [x] configuration_helper @yvaucher #411 
- [x] cron_run_manually #380 (Deleted because is now on core)
- [x] database_cleanup - By @hbrunn - #469
- [x] datetime_formatter - By @cubells - #605 
- [x] dbfilter_from_header - #382
- [x] disable_openerp_online > disable_odoo_online - #399
- [ ] email_template_template
- [ ] fetchmail_attach_from_folder
- [ ] fetchmail_notify_error_to_sender
- [x] html_image_url_extractor - @cubells - #624 
- [x] html_text - @cubells - #625
- [ ] import_odbc
- [x] inactive_session_timeout > auth_session_timeout - #379
- [ ] ir_config_parameter_viewer
- [ ] language_path_mixin
- [x] mail_environment #335
- [x] mass_editing (WIP #315, #320)
- [x] module_prototyper by @njeudy in #318
- [x] ~~qweb_usertime~~ - Not needed as stated in https://github.com/OCA/server-tools/pull/700#issuecomment-272873383
- [ ] save_translation_file
- [x] scheduler_error_mailer - by @atchuthan - #429
- [ ] security_protector
- [ ] server_env_base_external_referentials
- [x] server_environment  #337
- [x] server_environment_files_sample #337
- [x] <s>shell</s> #306 
- [ ] super_calendar - By @JayVora-SerpentCS - #528 
- [ ] users_ldap_groups
- [ ] users_ldap_mail
- [x] users_ldap_populate
- [ ] users_ldap_push
- [ ] web_context_tunnel (wip by @atchuthan)

**Comment by pedrobaeza** [comment]
I think _qweb_usertime_ should be in reporting-engine repo and be called _report_qweb_usertime_

**Comment by dvdhinesh** [comment]
inactive_session_timeout available #379

**Comment by atchuthan** [comment]
For info, we started porting base_multi_image.

**Comment by pedrobaeza** [comment]
Cool, I write it on the main section.

**Comment by atchuthan** [comment]
For info, we started migrating web_context_tunnel and scheduler_error_mailer.

**Comment by yvaucher** [comment]
@atchuthan Thanks I added you on scheduler_error_mailer

**Comment by yajo** [comment]
I'm starting with auth_supplier

**Comment by yajo** [comment]
I'm starting with base_custom_info

**Comment by yajo** [comment]
Starting with auth_signup_verify_email

**Comment by lmignon** [comment]
Starting `auth_from_http_remote_user`

**Comment by JayVora-SerpentCS** [comment]
#528 For super_calendar

**Comment by atchuthan** [comment]
The dependency for sale_rental module had web_context_tunnel in previous versions, but not in 9.0.
So, I didn't migrate web_context_tunnel. (forgot to leave a comment in this thread :P)

**Comment by pedrobaeza** [comment]
web_context_tunnel has no more sense in new API onchanges.

**Comment by rvalyi** [comment]
I agree with @pedrobaeza

**Comment by andreparames** [comment]
@pedrobaeza @rvalyi while it was made for onchanges, doesn't `web_context_tunnel` still make sense for other uses of `context` in the view, like adding extra default fields to ` <field name="...." context="{'default_...`? Is there a better way to solve this? Odoo attributes not being composable is a frustratingly common problem.

**Comment by pedrobaeza** [comment]
@andreparames yes, they are residual uses, but the module can be useful for that.

**Comment by andreparames** [comment]
@pedrobaeza thanks, just wanted to make sure I wasn't missing something. I think I'll migrate it and reword the description.

**Comment by alecvinent** [comment]
I'd like to contribute.

**Comment by pedrobaeza** [comment]
@alecvinent in what do you want to contribute? Migrate a certain module? Just tell us to assign you in this issue for avoiding duplicating efforts and start when you want.

**Comment by alecvinent** [comment]
@pedrobaeza I've been checking auth_admin_passkey module issues, so I can work with it.

**Comment by pedrobaeza** [comment]
OK, you can check v10 version which is migrated for starting with that instead: https://github.com/OCA/server-tools/tree/10.0/auth_admin_passkey

**Comment by pedrobaeza** [comment]
Hey, I'm seeing that there's already a migration in #522. Review that one instead.
