### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/server-tools#565]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] admin_technical_features
- [x] attachment_base_synchronize - By @florian-dacosta - #763 
- [x] auditlog - By @BT-fgarbely - #707  
- [x] auth_admin_passkey - By @Fenkiou - #776
- [x] auth_brute_force - By @chienandalu - #877 
- [x] auth_dynamic_groups - By @hbrunn - #1575, https://github.com/OCA/server-auth/pull/96
- [ ] auth_from_http_basic
- [ ] auth_from_http_basic_logout
- [ ] auth_from_http_remote_user - By @Olivier-LAURENT - #1269 
- [x] auth_session_timeout - By @lasley - #580 
- [ ] auth_signup_verify_email - By @sharkende - #718 
- [x] auth_supplier - By @StephanRozendaal - #793
- [x] base_custom_info - By @fanha99 - #1115 
- [x] base_import_match - By @Yajo - #871
- [x] ~~base_debug4all~~ - Feature already on core
- [x] base_export_manager - By @Yajo - #870 
- [x] base_external_dbsource - By @jlzhou - #578 
- [x] base_multi_image - #600 
- [x] base_optional_quick_create - By @alexis-via - #597 
- [x] base_report_auto_create_qweb - By @grindtildeath - #808
- [x] base_search_fuzzy - By @lasley - #722 
- [x] base_suspend_security - By @adrienpeiffer - #586 
- [x] base_technical_features - By @StefanRijnhart - #568
- [x] base_user_gravatar - @lasley #584 
- [ ] base_user_reset_access - By @adrienpeiffer - #574 
- [x] base_user_role - By @adrienpeiffer - #684 
- [x] configuration_helper - By @angelmoya - #798
- [x] database_cleanup - ~~By @eantones - #607~~ By @ecino - #607 
- [x] date_range - By @espo-tony - #567 
- [x] datetime_formatter - By @Yajo - #872
- [x] dbfilter_from_header - By @JosDeGraeve - #571 
- [ ] dead_mans_switch_client
- [X] disable_odoo_online - By @legalsylvain - #583
- [ ] email_template_template
- [ ] external_file_location - By @cmsalmeida - #926
- [ ] fetchmail_attach_from_folder
- [x] fetchmail_notify_error_to_sender
- [x] html_image_url_extractor - By @Yajo - #873
- [x] html_text - By @Yajo - #874
- [ ] import_odbc
- [ ] ir_config_parameter_viewer
- [ ] language_path_mixin
- [x] letsencrypt - By @robyf70 - #840 
- [x] mail_environment - By @guewen - #662 
- [x] mass_editing - By @JayVora-SerpentCS - #598 
- [ ] menu_technical_info
- [ ] mgmtsystem_kpi
- [x] module_prototyper - By @tarteo - #634 
- [x] password_security - By @lasley - #579 
- [x] ~~qweb_usertime~~ - Removed as not needed on core - #834 
- [x] res_config_settings_enterprise_remove - By @mstuttgart - #665
- [x] scheduler_error_mailer - By @EBII - #725 
- [ ] security_protector
- [ ] server_env_base_external_referentials
- [x] server_environment - By @adrienpeiffer - #595 
- [ ] server_environment_files_sample
- [x] server_environment_ir_config_parameter - @rousseldenis #640
- [ ] super_calendar - By @jeanpaulrobineau - #609 
- [ ] test_configuration_helper
- [ ] users_ldap_groups - By @hbrunn - #1144 
- [x] users_ldap_mail - By @StephanRozendaal - #651 
- [x] users_ldap_populate - By @StephanRozendaal - #657
- [x] ~~web_context_tunnel~~ - No more needed as there's no old API

**Comment by tarteo** [comment]
Can you assign module_prototyper to me, please. Thank you!

**Comment by pedrobaeza** [comment]
Done

**Comment by StephanRozendaal** [comment]
Can you assign users_ldap_mail and users_ldap_populate to me? Thanks!

**Comment by lasley** [comment]
@StephanRozendaal done

**Comment by aktaaf** [comment]
Hi all,

I need auditlog on odoo 10.0 commnuity.
The module can be installed on odoo 10 successfully but there will be no  "Reporting / Audit / Rules" menu!

Any help will be appreciated.

Thank you in advance
Aktaaf

**Comment by sharkende** [comment]
Hi,
Can you assign auth_signup_verify_email to me ? Thanks a lot !

**Comment by pedrobaeza** [comment]
Done

**Comment by jvOrsouw** [comment]
I'm having trouble creating date ranges. The regular months is no problem, but I also would like an opening period from 01-01-2017 to 01-01-2017. I get an error saying that end date must be later than start date.

**Comment by StephanRozendaal** [comment]
Just sent a pull request for the auth_supplier module.

**Comment by lasley** [comment]
Thanks @StephanRozendaal - tagged you to it

**Comment by cmsalmeida** [comment]
Hi I'll migrate:
- attachment_base_synchronize
- external_file_location

**Comment by florian-dacosta** [comment]
@cmsalmeida 
There is an existing PR for attachment_base_synchronize : 
https://github.com/OCA/server-tools/pull/763

You can review it.

For external_file_location, no PR for now, feel free to migrate it indeed.
Thank you

**Comment by cmsalmeida** [comment]
Hi,
I'll migrate:
 - attachment_base_synchronize
 - external_file_location
(the last even not be in list)

**Comment by cmsalmeida** [comment]
@florian-dacosta 
I didn't saw it in top list.
But how could I migrate external_file_location without migrating attachment_base_synchronize dependency?
How to have both in same branch?

**Comment by Garamotte** [comment]
You can create a branch based on the PR's branch, and rebase on 10.0 when the PR is merged.

**Comment by cmsalmeida** [comment]
git fetch origin refs/pull/763/head:10.0-mig-external_file_location
git format-patch --stdout origin/10.0..origin/9.0 -- external_file_location | git am -3
would this be ok? so I can start migrating...

**Comment by yajo** [comment]
Here you have the docs for checking out a PR locally: https://help.github.com/articles/checking-out-pull-requests-locally/
And here to migrate an addon to v10: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
😊

**Comment by flachica** [comment]
I want to migrate the kpi module. To make the announcement that is commented [here](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0) is this comment enough?

**Comment by pedrobaeza** [comment]
Yes, it's enough :smiley: Check #1423 for possible similarities
